---
driver:
  name: vagrant

  provisioner:
    name: chef_zero

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: debian/jessie64

suites:
  - name: default
    run_list:
    - recipe[cas_cron::default]
    attributes: 
      cas_cron:
        jobs:
          test1:
            environment:
              HOME: '/var/www/html/'
              PATH: '/sbin:/bin:/usr/sbin:/usr/bin'
            predefined_value: '@weekly'
            user: 'root'
            command: '/bin/true'
          test2:
            comment: "This is a test comment"
            minute: 1
            hour: 2
            day: 3
            month: 4
            user: 'root'
            command: '/bin/false'
